import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { registerTrial } from '@/lib/supabaseClient';

export async function POST(request: Request) {
  try {
    const data = await request.json();

    // 1. Server-side validation (Spam prevention check)
    if (
      !data.player_name ||
      !data.parent_name ||
      !data.age ||
      !data.phone ||
      !data.email ||
      !data.city ||
      !data.experience ||
      !data.preferred_batch ||
      !data.preferred_day
    ) {
      return NextResponse.json(
        { success: false, error: 'Missing required registration fields' },
        { status: 400 }
      );
    }

    // Basic spam honeypot validation
    if (data.website) {
      // If honeypot 'website' field is populated, silently reject as spam
      return NextResponse.json({ success: true, spamBlocked: true });
    }

    // 2. Insert into Supabase
    const dbResult = await registerTrial({
      player_name: data.player_name,
      parent_name: data.parent_name,
      age: parseInt(data.age),
      phone: data.phone,
      email: data.email,
      city: data.city,
      experience: data.experience,
      preferred_batch: data.preferred_batch,
      preferred_day: data.preferred_day,
      message: data.message || '',
    });

    // 3. Email sending setup
    const smtpUser = process.env.SMTP_USER || 'sportizen.sports@gmail.com';
    const smtpPass = process.env.SMTP_PASS || '';
    const recipientEmail = 'sportizen.sports@gmail.com';

    const htmlBody = `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 10px;">
        <h2 style="color: #0E2240; border-bottom: 2px solid #F47A20; padding-bottom: 10px; margin-top: 0;">🏀 New Trial Class Registration</h2>
        <p>A new student has registered for a free trial class at <strong>Sportizen Basketball Academy</strong>. Below are the registration details:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr style="background-color: #f8f9fa;">
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; width: 40%;">Player Name</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.player_name}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Parent Name</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.parent_name}</td>
          </tr>
          <tr style="background-color: #f8f9fa;">
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Age</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.age}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Phone Number</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.phone}</td>
          </tr>
          <tr style="background-color: #f8f9fa;">
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Email Address</td>
            <td style="padding: 10px; border: 1px solid #eee;"><a href="mailto:${data.email}">${data.email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">City</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.city}</td>
          </tr>
          <tr style="background-color: #f8f9fa;">
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Experience Level</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.experience}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Preferred Batch</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.preferred_batch}</td>
          </tr>
          <tr style="background-color: #f8f9fa;">
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold;">Preferred Days</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.preferred_day}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; vertical-align: top;">Message</td>
            <td style="padding: 10px; border: 1px solid #eee; white-space: pre-wrap;">${data.message || 'No additional message'}</td>
          </tr>
        </table>
        
        <p style="margin-top: 20px; font-size: 11px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 10px;">
          This message was auto-generated by the Sportizen Academy registration system.
        </p>
      </div>
    `;

    if (smtpUser && smtpPass) {
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: smtpUser,
          pass: smtpPass,
        },
      });

      await transporter.sendMail({
        from: `"Sportizen Academy" <${smtpUser}>`,
        to: recipientEmail,
        subject: `🏀 Trial Registration: ${data.player_name}`,
        html: htmlBody,
      });

      console.log(`Email dispatched successfully to ${recipientEmail}`);
    } else {
      console.log('SMTP Config Missing. Logged email data:');
      console.log(`Recipient: ${recipientEmail}`);
      console.log(`Content HTML:\n${htmlBody}`);
    }

    return NextResponse.json({ success: true, dbSaved: dbResult.success });
  } catch (error: any) {
    console.error('API registration handling failure:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Internal server error occurred' },
      { status: 500 }
    );
  }
}
